### ISSUE TITLE
내가 속한 동아리명을 가져 올 수 있어야 함.

### ISSUE THREAD

**Issue by jeongmincha** [round-up/roundup_server#3]
로그인 > 홈 피드 > 네비게이션 바를 열었을 때, 내가 속한 동아리들이 무엇이 있는지 알아야 함.

입력: user_id
출력: 속한 동아리들 이름, id

할 수 있는 API콜이 필요함.

**Comment by AppleHolic** [comment]
- 작업 순서
- group 기수 및 직책 정보 manager
- group member manager
- call test
- 자신이 리더인 경우 및 그룹 소속원인 모든 그룹 가져 올 수 있는 기능 및 url

**Comment by jeongmincha** [comment]
음? ㅋㅋㅋ 무슨 말인가요 그렇게 작업을 하겠다는..?

**Comment by AppleHolic** [comment]
응 ㅋㅋ 적어놓으려구 했어

**Comment by AppleHolic** [comment]
- 서버 작업 완료, 안드로이드 테스트 진행
- android 작업 완료, 렐름 관련 재코딩 필요~
