### ISSUE TITLE
홈피드를 구성하기 위한 데이터를 가져오는 API 콜이 필요함.

### ISSUE THREAD

**Issue by jeongmincha** [round-up/roundup_server#4]
로그인 > 홈 피드 했을 때,
1. 내가 속한 동아리의 활동들 요약 카드
2. 핫한 동아리 활동 피드들
가 보여져야 함.

1.
입력: user_id
출력: list(동아리 명, 날짜, 세션 피드들의 제목들)

2.
입력: user_id
출력: list(피드의 모든 정보)
(핫한 동아리 활동 피드를 가져오는 알고리즘이 아직 구현안됬으니깐, 적당하게 피드 몇 개 던져주면 됨)
(피드 모든 정보 = 동아리명, 작성자명, 피드 제목, 피드 내용, 피드 이미지들, 좋아요, 댓글 등...)

**Comment by jeongmincha** [comment]
1,2 에대 한 콜메서드가 필요하다는 이야기에용

**Comment by AppleHolic** [comment]
- 작업 순서
- 피드 manager
- 샘플 피드 삽입
- 리스트 2가지 타입으로 리턴, 요약 정보, 핫한 순으로 피드 모든 정보

**Comment by AppleHolic** [comment]
- 둘 다 피드 id값도 저장해야 할 것 같음.
  - 피드 눌렀을 시 피드 페이지 넘어가려면 아이디 값으로 피드 정보 로딩해야 할 듯.

**Comment by jeongmincha** [comment]
홈 피드는 home/HomeActivity.java를 보시면 되는데요.
지금 이 홈 피드는 리사이클러 뷰 2개를 써서 2개의 다른 종류의 피드를 다루고 있습니다.
1번 기능의 경우, 첫번째 리사이클러뷰에 들어갈 뷰 홀더들의 내용을 불러오기 위한 용도이고요 (그룹 요약)
2번 기능의 경우, 두번째 리사이클러뷰에 들어갈 뷰 홀더들의 내용을 불러오기 위한 용도에요. (Hot Content)

**Comment by AppleHolic** [comment]
기능 완료, 이미지를 여러 장 넣는 일은 모델 수정이 필요하여 바로 작업 들어가겠음.

**Comment by AppleHolic** [comment]
Image , comment, likes complete!
