### ISSUE TITLE
자세히 보기 콜 API 가 필요함.

### ISSUE THREAD

**Issue by kyeongwan** [round-up/roundup_server#5]
홈 피드 > 동아리 피드 > 동아리 자세히보기 했을 때,
1. 동아리 정보
2. 회원들 사진
1.
입력: 동아리id
출력: list(동아리 명, 많은 정보, 회원 명부)

**Comment by AppleHolic** [comment]
- 작업 순서
- 동아리 정보 샘플 삽입
- 여러 명의 유저 샘플 삽입 및 동일 동아리에 가입 데이터
- 동아리 디테일 정보 요청시, 동아리 정보, 가입한 사람 목록 반환

**Comment by AppleHolic** [comment]
기능 구현 완료

![image](https://cloud.githubusercontent.com/assets/3727290/16082277/ccc779e0-334b-11e6-802f-dff0c27fa01f.png)

**Comment by AppleHolic** [comment]
명세에 콜 요청 방식 업데이트 하겠음!
