### ISSUE TITLE
동아리 피드 콜 API

### ISSUE THREAD

**Issue by kyeongwan** [round-up/roundup_server#6]
동아리 커버사진
동아리 프로필 사진
동아리 이름
동아리 id
동아리 연합그룹 목록, 총 회원수
몇기인지, 장소는 어디서 모이는지

게시물 목록
제목, 작성자, 내용, 일시, 사진이있는지여부, 있으면 몇장인지, 추천수, 댓글수

**Comment by AppleHolic** [comment]
연합 그룹 기능 추가 이후 function추가 하겠음

**Comment by AppleHolic** [comment]
구현 완료
