### ISSUE TITLE
네비게이션 드로워 구성할 때 그 사람의 프로필 사진 가져오도록 해야 할듯.

### ISSUE THREAD

**Issue by jeongmincha** [round-up/roundup_server#8]
NavigationDrawerActivity에서 그 사람 프로필 사진 가져오도록 해야 함.
배경화면은 굳이 안 가져와도 됨. 네비게이션 드로워에서까지 사용자 배경화면까진 안가져와도 됨
1. 입력: user_id
2. 출력: 사용자 프로필 사진

너무 간단한 거라 이미 만들어놨을지도...? ㅋㅋㅋ
각 데이터 인스턴스들 필드 하나하나씩 다 가져올 수 있는 API콜만 짜놨어도 이건 바로 되는거니 ㅋㅋㅋ 
그래도 혹시 몰라서 남겨놉니다

**Comment by AppleHolic** [comment]
필드에 포함토록 하겠음.! 잠만

**Comment by AppleHolic** [comment]
![image](https://cloud.githubusercontent.com/assets/3727290/16008688/21fbd3aa-31b4-11e6-871c-1e3ceb1f2bbc.png)
유저 정보 가져오는 서버 기능은 있구, 클라이언트 코딩만 하면 됨.
걍 로그인 하면 해당 유저 정보 다들고 계속 공유해야는거 아니야?
